[versions]
morphe-patcher = "1.13.0"
#noinspection GradleDependency
smali = "d92701d947"
gson = "2.14.0"
junit = "5.14.4"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
# Gradle plugins adds the dependency during build, this declaration is here only for dependabot to provide updates.
#noinspection UnusedVersionCatalogEntry
morphe-patcher = { module = "app.morphe:morphe-patcher", version.ref = "morphe-patcher" }
